### ISSUE TITLE
Attempting to call unbound fn: # clojure.future/ident?

### ISSUE THREAD

**Issue by didibus** [tonsky/clojure-future-spec#11]
This seems to happen now that I switched to Clojure 1.9

It seems to be caused by a call to `Class.forName("clojure.java.api.Clojure");` from Java.

**Comment by tonsky** [comment]
Thx I’ll take a look

**Comment by piotr-kozbial** [comment]
I have the same with clojure 1.10.0.

**Comment by didibus** [comment]
I actually figured out the issue. It was caused by one of my dependencies being AOT compiled with different versions of Clojure.

**Comment by piotr-kozbial** [comment]
Thank you. I was just plain stupid and put my comment in a wrong place, but you answer pointed me in the right direction so I could fix my problem.
